services:
  vulnerable-app:
    build:
      context: .
      dockerfile: vulnerable-app/Dockerfile
    container_name: vulnshop-vulnerable
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - vulnshop_vulnerable_net
    restart: unless-stopped

  secure-app:
    build:
      context: .
      dockerfile: secure-app/Dockerfile
    container_name: vulnshop-secure
    env_file:
      - .env
    ports:
      - "5001:5000"
    networks:
      - vulnshop_secure_net
    restart: unless-stopped

networks:
  vulnshop_vulnerable_net:
    driver: bridge
    internal: true
  vulnshop_secure_net:
    driver: bridge
    internal: true
