services:
  vulnerable-app:
    build:
      context: .
      dockerfile: vulnerable-app/Dockerfile
    container_name: vulnshop-vulnerable
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - APP_MODE=vulnerable
    volumes:
      - vulnerable_data:/app/data
    networks:
      - vulnshop_vulnerable_net

  secure-app:
    build:
      context: .
      dockerfile: secure-app/Dockerfile
    container_name: vulnshop-secure
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - APP_MODE=secure
    volumes:
      - secure_data:/app/data
    networks:
      - vulnshop_secure_net

volumes:
  vulnerable_data:
  secure_data:

networks:
  vulnshop_vulnerable_net:
    driver: bridge

  vulnshop_secure_net:
    driver: bridge
